# pg_tre - PostgreSQL extension: native index AM for approximate regex
#
# Build orchestration:
#   1. Build TRE (statically) from the vendored submodule via its autotools.
#   2. Build the Lime parser generator (single-file C) from the submodule.
#   3. Generate src/query/tre_grammar.{c,h} from src/query/tre_grammar.y.
#   4. Compile sparsemap, pg_tre source tree, and the generated parser into
#      the PGXS-driven shared library.
#
# Requires PostgreSQL 18 or newer.  Override PG_CONFIG to pick an install.
#
#   make PG_CONFIG=~/.pgrx/18.3/pgrx-install/bin/pg_config
#   make PG_CONFIG=~/.pgrx/18.3/pgrx-install/bin/pg_config install
#   make PG_CONFIG=~/.pgrx/18.3/pgrx-install/bin/pg_config installcheck
#

EXTENSION    = pg_tre
MODULE_big   = pg_tre
DATA         = sql/pg_tre--1.0.0.sql sql/pg_tre--0.1.0--1.0.0.sql
DATA_built   =
REGRESS      = pg_tre
REGRESS_OPTS = --inputdir=test --outputdir=test

# ------------------------------------------------------------------
# Vendored submodules
# ------------------------------------------------------------------
TRE_DIR   = vendor/tre
LIME_DIR  = vendor/lime

TRE_LIB        = $(TRE_DIR)/lib/.libs/libtre.a
TRE_CONFIGURE  = $(TRE_DIR)/configure
TRE_CONFIG_H   = $(TRE_DIR)/config.h
LIME_BIN       = $(LIME_DIR)/lime

# Grammar artifacts generated by Lime.
GRAMMAR_Y   = src/query/tre_grammar.y
GRAMMAR_C   = src/query/tre_grammar.c
GRAMMAR_H   = src/query/tre_grammar.h

# ------------------------------------------------------------------
# pg_tre source files (compiled into MODULE_big)
# ------------------------------------------------------------------
OBJS = \
    src/module.o \
    src/util/pattern_cache.o \
    src/util/tre_match.o \
    src/util/sparsemap.o \
    src/util/bloom.o \
    src/util/hash.o \
    src/util/type_pattern.o \
    src/am/amapi.o \
    src/am/ambuild.o \
    src/am/aminsert.o \
    src/am/amscan.o \
    src/am/amvacuum.o \
    src/am/amcost.o \
    src/am/amoptions.o \
    src/pages/buffer.o \
    src/pages/meta.o \
    src/pages/upper.o \
    src/pages/posting.o \
    src/pages/pending.o \
    src/pages/range.o \
    src/wal/xlog.o \
    src/query/tre_grammar.o \
    src/query/tokens.o \
    src/query/parser.o \
    src/query/regex_ast.o \
    src/query/extract.o \
    src/query/debug.o
#   src/query/tiling.o  -- Phase 5 READ side, uncomment when integrating
#   src/query/uleven.o  -- Phase 5 READ side, uncomment when integrating

# Sparsemap is vendored in-tree; silence upstream missing-prototype
# warnings without disabling them globally.
src/util/sparsemap.o: CFLAGS += -Wno-missing-prototypes

# Grammar-generated files may have warnings; disable pedantic checks.
src/query/tre_grammar.o: CFLAGS += -Wno-unused-parameter -Wno-missing-prototypes

# ------------------------------------------------------------------
# Include paths & compile flags
# ------------------------------------------------------------------
PG_CPPFLAGS = \
    -I$(srcdir)/include \
    -I$(srcdir)/$(TRE_DIR)/local_includes \
    -I$(srcdir)/$(TRE_DIR) \
    -Wno-declaration-after-statement

# Link TRE statically.
SHLIB_LINK = $(TRE_LIB) -lm

PG_CONFIG ?= pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)

# ------------------------------------------------------------------
# PG version guard: require >= 18.
# ------------------------------------------------------------------
PG_VERSION_RAW := $(shell $(PG_CONFIG) --version 2>/dev/null)
PG_MAJOR := $(shell echo '$(PG_VERSION_RAW)' | awk '{print $$2}' | cut -d. -f1)
ifeq ($(PG_MAJOR),)
$(error Could not determine PostgreSQL major version from PG_CONFIG=$(PG_CONFIG))
endif
ifeq ($(shell test $(PG_MAJOR) -lt 18 2>/dev/null && echo yes),yes)
$(error pg_tre requires PostgreSQL 18 or newer; found $(PG_MAJOR))
endif

# ------------------------------------------------------------------
# TRE static build
# ------------------------------------------------------------------
$(TRE_CONFIGURE): $(TRE_DIR)/configure.ac
	@echo "==> autoreconf TRE"
	cd $(TRE_DIR) && ./utils/autogen.sh >/dev/null

$(TRE_CONFIG_H): $(TRE_CONFIGURE)
	@echo "==> configure TRE"
	cd $(TRE_DIR) && ./configure \
	    --enable-static --disable-shared --disable-nls \
	    --without-alloca \
	    CFLAGS="-fPIC -O2 -g" >/dev/null

$(TRE_LIB): $(TRE_CONFIG_H)
	@echo "==> build TRE"
	$(MAKE) -C $(TRE_DIR) >/dev/null

# ------------------------------------------------------------------
# Lime generator
# ------------------------------------------------------------------
$(LIME_BIN): $(LIME_DIR)/lime.c
	@echo "==> build Lime generator"
	$(CC) -O2 -o $@ $<

# ------------------------------------------------------------------
# Grammar codegen
# ------------------------------------------------------------------
$(GRAMMAR_C) $(GRAMMAR_H): $(GRAMMAR_Y) $(LIME_BIN)
	@echo "==> generate regex parser"
	$(LIME_BIN) -q -T$(LIME_DIR)/limpar.c -d$(@D) $<

# Dependency: our objects on TRE's config, shlib on the static archive.
src/util/tre_match.o src/util/pattern_cache.o src/module.o: $(TRE_CONFIG_H)
pg_tre.so: $(TRE_LIB)

# Query path depends on generated grammar.
src/query/tokens.o src/query/extract.o: $(GRAMMAR_H)
src/query/tre_grammar.o: $(GRAMMAR_C) $(GRAMMAR_H)

# ------------------------------------------------------------------
# Convenience targets
# ------------------------------------------------------------------
.PHONY: localcheck vendor-clean distclean-full

# Local regression runner that sidesteps our nix-build pg_regress
# exec-path quirk.  Invokes scripts/run-regress.sh against an already-
# running postmaster (must have pg_tre in shared_preload_libraries).
# Named localcheck to avoid overriding PGXS's standard `check` target.
localcheck:
	PG_CONFIG='$(PG_CONFIG)' $(SHELL) scripts/run-regress.sh

vendor-clean:
	-$(MAKE) -C $(TRE_DIR) distclean 2>/dev/null || true
	rm -f $(LIME_BIN)

distclean-full: clean vendor-clean
	rm -f $(GRAMMAR_C) $(GRAMMAR_H)

clean: clean-grammar

clean-grammar:
	rm -f $(GRAMMAR_C) $(GRAMMAR_H) src/query/tre_grammar.o
