/*
 * src/query/tokens.c - hand-written regex tokenizer.
 *
 * Lime handles the grammar (LALR(1)); this file emits tokens the
 * grammar consumes.  Regex requires mode-sensitive lexing (inside
 * [...] a '-' is a range operator, outside it's a literal; inside
 * {~m} the contents are a count) so a mode-free generated tokenizer
 * is not a great fit -- hence the hand roll.
 *
 * Phase 3: ASCII-only support. Multi-byte UTF-8 sequences are handled
 * in Phase 3.5. For Phase 3, each "codepoint" is a single byte.
 */

#include "postgres.h"

#include "miscadmin.h"

#include "pg_tre/regex_ast.h"
#include "pg_tre/utf8.h"

#include <ctype.h>

/* Token IDs from tre_grammar.h (generated by Lime). */
#define TOK_PIPE          1
#define TOK_CONCAT        2
#define TOK_STAR          3
#define TOK_PLUS          4
#define TOK_QUESTION      5
#define TOK_LBRACE        6
#define TOK_APPROX        7
#define TOK_INT           8
#define TOK_RBRACE        9
#define TOK_COMMA         10
#define TOK_LPAREN        11
#define TOK_RPAREN        12
#define TOK_LITERAL       13
#define TOK_DOT           14
#define TOK_ANCHOR_START  15
#define TOK_ANCHOR_END    16
#define TOK_LBRACKET      17
#define TOK_RBRACKET      18
#define TOK_CARET         19
#define TOK_DASH          20

/* parse_escape: the escape was a class shorthand (\d, \w, \s, ...). */
#define PG_TRE_ESC_CLASS  (-2)
/* parse_escape: an escape whose meaning the index cannot rely on (\x41,
 * \m, \1, ...).  Zero or one character: not even a wildcard is safe. */
#define PG_TRE_ESC_OPAQUE (-3)

typedef enum TokenizerMode
{
	MODE_NORMAL,
	MODE_BRACKET,      /* inside [...] */
	MODE_BRACE,        /* inside {m,n} or {~N} */
	MODE_BRACE_APPROX  /* inside {~N} after seeing ~ */
} TokenizerMode;

typedef struct TokenizerState
{
	const char *input;
	int         len;
	int         pos;
	TokenizerMode mode;
	int         bracket_depth;
	int         brace_depth;
	/*
	 * Byte offset of the first member position of the current bracket
	 * expression, i.e. just past '[' and any leading '^'.  POSIX makes '-'
	 * a literal (not a range operator) when it is the FIRST or LAST member
	 * of a bracket expression, so `[-_]`, `[abc-]` and `[-]` are all valid
	 * and mean a literal dash.  Emitting TOK_DASH unconditionally left the
	 * grammar unable to reduce them and the whole pattern was rejected as
	 * "invalid regex pattern" -- which took out a caller's word-boundary
	 * pattern `(^|[-_.])git([-_.0-9]|$)` entirely.
	 */
	int         bracket_first;
	/* The current bracket held a [:class:], [=e=], [.c.] or \w-style
	 * member, so its membership is collation-dependent: treat as '.'. */
	bool        bracket_opaque;
} TokenizerState;

/*
 * Initialize tokenizer state.
 */
static void
init_tokenizer(TokenizerState *ts, const char *input, int len)
{
	ts->input = input;
	ts->len = len;
	ts->pos = 0;
	ts->mode = MODE_NORMAL;
	ts->bracket_depth = 0;
	ts->brace_depth = 0;
	ts->bracket_first = -1;
}

/*
 * Peek at the next character without consuming it.
 */
static int
peek_char(TokenizerState *ts)
{
	PgTreCpStream s;
	if (ts->pos >= ts->len)
		return -1;
	pg_tre_cpstream_init(&s, ts->input + ts->pos, ts->len - ts->pos);
	return pg_tre_cpstream_next(&s);   /* decode, don't advance ts->pos */
}

/*
 * Consume and return the next codepoint (UTF-8 aware).
 *
 * Phase 3.5: decode codepoints, not raw bytes, so a multi-byte UTF-8
 * character produces a single LITERAL token whose `cp` matches the
 * codepoints emitted by ambuild's cpstream tokenizer.
 */
static int
next_char(TokenizerState *ts)
{
	PgTreCpStream s;
	int cp;
	if (ts->pos >= ts->len)
		return -1;
	pg_tre_cpstream_init(&s, ts->input + ts->pos, ts->len - ts->pos);
	cp = pg_tre_cpstream_next(&s);
	if (cp >= 0)
		ts->pos += s.src_pos;
	return cp;
}

/*
 * Parse an escape sequence starting after the backslash.
 * Returns the escaped codepoint or -1 on error.
 */
static int
parse_escape(TokenizerState *ts, TreParseCtx *ctx)
{
	int c = next_char(ts);

	switch (c)
	{
		case 'n': return '\n';
		case 't': return '\t';
		case 'r': return '\r';
		case '\\': return '\\';
		case '.': return '.';
		case '[': return '[';
		case ']': return ']';
		case '(': return '(';
		case ')': return ')';
		case '{': return '{';
		case '}': return '}';
		case '|': return '|';
		case '*': return '*';
		case '+': return '+';
		case '?': return '?';
		case '^': return '^';
		case '$': return '$';
		case '-': return '-';

		/*
		 * Class shorthands: \d \w \s and their negations.  Their meaning
		 * depends on the collation (which letters are "word" characters),
		 * and the index only needs to know that ONE character sits here,
		 * so report a wildcard; the executor's recheck applies the real
		 * class.  Previously these raised "not yet implemented" -- only
		 * on the index path, so the same query errored or succeeded
		 * depending on the plan.
		 */
		case 'd': case 'D':
		case 'w': case 'W':
		case 's': case 'S':
			return PG_TRE_ESC_CLASS;

		case -1:
			ctx->syntax_error = true;
			snprintf(ctx->errmsg, sizeof(ctx->errmsg),
					 "unexpected end of pattern after backslash");
			return -1;

		/* Escapes for a literal punctuation/space character.  ('<' and '>'
		 * are NOT here: in TRE \< and \> are word anchors.) */
		case ' ': case '#': case '&': case '\'': case '"': case ',':
		case ':': case ';': case '=': case '@':
		case '_': case '`': case '~': case '!': case '%': case '/':
			return c;

		case '<': case '>':
			return PG_TRE_ESC_OPAQUE;

		default:
			/*
			 * Everything else is CONSERVATIVE.  The pattern is rechecked by
			 * TRE (%~~) or by core's regex engine (~, ~*), whose escape
			 * syntax differ, and a wrong guess here makes the index demand
			 * a trigram the row lacks -- silently dropping rows.  Letter and
			 * digit escapes mean something in at least one of them:
			 * character codes (\x41, \u00e9, \0101, \e, \f, \v, \a),
			 * class shorthands, word/string anchors (\m \M \y \Y \A \Z
			 * \b \B \< \>) and back-references (\1 ..).  Inside a bracket
			 * that makes the bracket one opaque character; elsewhere the
			 * whole pattern goes unindexed (lossy scan + recheck).
			 */
			if (c >= 0 && c < 128 && isalnum(c))
			{
				/* \xHH / \uHHHH / \x{...} / \0nn: skip the digits too. */
				while (ts->pos < ts->len &&
				       (isxdigit((unsigned char) ts->input[ts->pos]) ||
				        ts->input[ts->pos] == '{' || ts->input[ts->pos] == '}') &&
				       (c == 'x' || c == 'u' || c == 'U' || c == '0'))
					ts->pos++;
				return PG_TRE_ESC_OPAQUE;
			}
			/* Any other (non-ASCII) escaped character is itself. */
			return c;
	}
}

/*
 * Parse a decimal integer starting at current position.
 * Returns the integer value and advances ts->pos.
 */
static int
parse_integer(TokenizerState *ts, TreParseCtx *ctx)
{
	int val = 0;
	int c;
	bool got_digit = false;

	while ((c = peek_char(ts)) != -1 && isdigit(c))
	{
		next_char(ts);
		val = val * 10 + (c - '0');
		got_digit = true;
	}

	if (!got_digit)
	{
		ctx->syntax_error = true;
		snprintf(ctx->errmsg, sizeof(ctx->errmsg),
				 "expected digit in repetition count");
		return -1;
	}

	return val;
}

/*
 * Main tokenization function.
 * Returns the token kind (> 0) or 0 on EOF, or -1 on error.
 */
int
tre_tokenize_next(TreParseCtx *ctx, TreToken *out)
{
	TokenizerState *ts;
	int c;

	/* Initialize tokenizer state on first call */
	if (ctx->tokenizer_state == NULL)
	{
		ts = (TokenizerState *) palloc0(sizeof(TokenizerState));
		init_tokenizer(ts, ctx->input, ctx->input_len);
		ctx->tokenizer_state = ts;
	}
	else
	{
		ts = (TokenizerState *) ctx->tokenizer_state;
	}

	/* EOF */
	if (ts->pos >= ts->len)
		return 0;

	/*
	 * Guard: every token must consume input.  next_char() reports a
	 * negative value without advancing on undecodable input; looping on it
	 * produced tokens forever (unbounded memory, no interrupt check) for
	 * EUC_TW 4-byte characters before utf8.c folded them into range.
	 */
	CHECK_FOR_INTERRUPTS();
	{
		int		before = ts->pos;

		c = next_char(ts);
		if (c < 0 || ts->pos == before)
		{
			ctx->syntax_error = true;
			snprintf(ctx->errmsg, sizeof(ctx->errmsg),
					 "undecodable character at byte offset %d", before);
			return -1;
		}
	}

	/* Handle mode-specific tokens */
	if (ts->mode == MODE_BRACKET)
	{
		/* Inside [...] */
		/*
		 * POSIX: a ']' that is the FIRST member (after '[' or '[^') is a
		 * literal, so `[]a]` and `[^]]` are valid.  Before this they ended
		 * the bracket immediately and the pattern failed to parse.
		 */
		if (c == ']' && ts->bracket_first >= 0 &&
		    ts->pos - 1 == ts->bracket_first)
		{
			ts->bracket_first = -1;
			out->cp = ']';
			return TOK_LITERAL;
		}
		if (c == ']')
		{
			ts->bracket_depth--;
			if (ts->bracket_depth == 0)
				ts->mode = MODE_NORMAL;
			out->i = ts->bracket_opaque ? 1 : 0;
			ts->bracket_opaque = false;
			return TOK_RBRACKET;
		}
		else if (c == '-')
		{
			/*
			 * POSIX: '-' is a range operator only BETWEEN two members.
			 * First or last in the bracket expression it is a literal, so
			 * `[-_.]`, `[abc-]` and `[-]` are legal.  ts->pos already points
			 * past this '-', so "last" means the next char closes the
			 * expression.
			 */
			bool at_first = (ts->bracket_first >= 0 &&
			                 ts->pos - 1 == ts->bracket_first);
			bool at_last = (ts->pos < ts->len && ts->input[ts->pos] == ']');

			if (at_first || at_last)
			{
				out->cp = '-';
				return TOK_LITERAL;
			}
			return TOK_DASH;
		}
		else if (c == '^')
		{
			/* ^ is CARET only at the start of the bracket expression */
			/* We'll let the parser handle the context */
			/* A negating '^' shifts where the first member begins, so a
			 * following '-' is still "first" (POSIX: `[^-x]`). */
			if (ts->bracket_first >= 0 && ts->pos - 1 == ts->bracket_first)
				ts->bracket_first = ts->pos;
			return TOK_CARET;
		}
		else if (c == '[' && ts->pos < ts->len &&
		         (ts->input[ts->pos] == ':' || ts->input[ts->pos] == '=' ||
		          ts->input[ts->pos] == '.'))
		{
			/*
			 * POSIX [:class:], [=equiv=] or [.coll.] inside a bracket
			 * expression.  Their members depend on the collation, so
			 * the index cannot enumerate them; skip to the closing
			 * ":]" / "=]" / ".]" and mark the whole bracket opaque.
			 * Before this the tokenizer read `[[:alpha:]]` as the set
			 * {[, :, a, l, p, h} followed by a LITERAL ']', and the
			 * index then demanded a trigram the row did not contain:
			 * matching rows were silently dropped.
			 */
			char	delim = ts->input[ts->pos];
			int		end = ts->pos + 1;

			while (end + 1 < ts->len &&
			       !(ts->input[end] == delim && ts->input[end + 1] == ']'))
				end++;
			if (end + 1 >= ts->len)
			{
				ctx->syntax_error = true;
				snprintf(ctx->errmsg, sizeof(ctx->errmsg),
						 "unterminated [%c in bracket expression", delim);
				return -1;
			}
			ts->pos = end + 2;
			ts->bracket_opaque = true;
			out->cp = 0;
			return TOK_LITERAL;
		}
		else if (c == '\\')
		{
			int esc = parse_escape(ts, ctx);
			if (esc == PG_TRE_ESC_CLASS || esc == PG_TRE_ESC_OPAQUE)
			{
				ts->bracket_opaque = true;
				out->cp = 0;
				return TOK_LITERAL;
			}
			if (esc < 0)
				return -1;
			out->cp = esc;
			return TOK_LITERAL;
		}
		else
		{
			out->cp = c;
			return TOK_LITERAL;
		}
	}
	else if (ts->mode == MODE_BRACE || ts->mode == MODE_BRACE_APPROX)
	{
		/* Inside {m,n} or {~N} */
		if (c == '}')
		{
			ts->brace_depth--;
			if (ts->brace_depth == 0)
				ts->mode = MODE_NORMAL;
			return TOK_RBRACE;
		}
		else if (c == ',')
		{
			return TOK_COMMA;
		}
		else if (c == '~' && ts->mode == MODE_BRACE)
		{
			ts->mode = MODE_BRACE_APPROX;
			/* Parse the integer that follows ~ */
			int k = parse_integer(ts, ctx);
			if (k < 0)
				return -1;
			out->i = k;
			return TOK_APPROX;
		}
		else if (isdigit(c))
		{
			/* Put the digit back and parse the full integer */
			ts->pos--;
			int val = parse_integer(ts, ctx);
			if (val < 0)
				return -1;
			out->i = val;
			return TOK_INT;
		}
		else
		{
			ctx->syntax_error = true;
			snprintf(ctx->errmsg, sizeof(ctx->errmsg),
					 "unexpected character '%c' inside {}", (char) c);
			return -1;
		}
	}

	/* Normal mode */
	switch (c)
	{
		case '|':
			return TOK_PIPE;

		case '*':
			return TOK_STAR;

		case '+':
			return TOK_PLUS;

		case '?':
			return TOK_QUESTION;

		case '(':
			/*
			 * Leading embedded options -- "(?i)", "(?n)", "(?-i)" and
			 * friends, which both TRE and core regex accept -- change how
			 * the rest of the pattern matches (case-insensitively, say), so
			 * the literal trigrams after them are no longer reliable.
			 * Treat the whole pattern as unindexable: the scan emits a
			 * fully lossy bitmap and the recheck decides, exactly as for
			 * ILIKE / ~*.  The grammar had no rule for "(?" and failed with
			 * an empty error message, on the index path only.
			 */
			if (ts->pos < ts->len && ts->input[ts->pos] == '?')
			{
				ctx->force_always_true = true;
				ts->pos = ts->len;      /* stop tokenizing */
				return TOK_DOT;
			}
			return TOK_LPAREN;

		case ')':
			return TOK_RPAREN;

		case '.':
			return TOK_DOT;

		case '^':
			return TOK_ANCHOR_START;

		case '$':
			return TOK_ANCHOR_END;

		case '[':
			ts->bracket_depth++;
			ts->mode = MODE_BRACKET;
			ts->bracket_first = ts->pos;   /* first member starts here */
			return TOK_LBRACKET;

		case '{':
			ts->brace_depth++;
			ts->mode = MODE_BRACE;
			return TOK_LBRACE;

		case '\\':
			{
				int esc = parse_escape(ts, ctx);
				if (esc == PG_TRE_ESC_CLASS)
					return TOK_DOT;     /* one character, class unknown */
				if (esc == PG_TRE_ESC_OPAQUE)
				{
					/*
					 * An escape the index cannot interpret (character codes,
					 * anchors, back-references): give up on trigram
					 * filtering for this pattern -- lossy bitmap, recheck
					 * decides -- rather than guess.  Same mechanism as
					 * "(?i)".  Rare in practice; never wrong.
					 */
					ctx->force_always_true = true;
					ts->pos = ts->len;
					return TOK_DOT;
				}
				if (esc < 0)
					return -1;
				out->cp = esc;
				return TOK_LITERAL;
			}

		default:
			/* Regular literal character */
			out->cp = c;
			return TOK_LITERAL;
	}
}
