-- pg_tre 2.0.0 -> 2.0.1-dev upgrade.
--
-- This stub is filled in as catalog-changing features land in
-- the dev cycle.  At release time, run the audit from
-- RELEASING.md to confirm every new CREATE FUNCTION /
-- OPERATOR / OPERATOR CLASS / TYPE / CAST / ALTER OPERATOR
-- FAMILY in sql/pg_tre--2.0.1-dev.sql has a matching statement
-- here, and every removed/renamed object has a matching
-- DROP / ALTER.
